import { CaseStudy } from "@/types";

// ============================================================================
// REFERENCE SCENARIOS — NOT CLIENT CASE STUDIES
//
// These are illustrative engagement blueprints: "how we'd approach X".
// Cloudrix is a new studio (founded 2026, KVK 97732699). We have NO named
// client case studies yet, and we won't invent them. Every entry below
// describes a realistic engagement — architecture, approach, stack, timeline,
// deliverables, and honest budget ranges — with zero invented outcome
// metrics, zero fabricated testimonials, and zero fake endorsements.
//
// The `client` field is intentionally labeled as illustrative. The `results`
// field lists concrete deliverables you would receive, not claimed outcomes.
// The `metrics` field holds factual engagement parameters (timeline, budget,
// staffing) — never performance numbers we can't prove.
// ============================================================================

export const referenceScenarioDisclaimer =
  "These are reference scenarios — illustrative engagement blueprints, not client claims. Cloudrix is a new studio (founded 2026); we'd rather show you exactly how we work than invent testimonials. Your project could be the first named case study — early clients get case-study pricing.";

export const caseStudies: CaseStudy[] = [
  {
    id: "1",
    slug: "nordic-payment-processor-migration",
    title: "How We'd Migrate a Payment Processor to the Cloud",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "Financial Services / FinTech",
    description:
      "An engagement blueprint for moving a high-volume, PCI-DSS-scoped payment platform from on-premise infrastructure to AWS — phased, reversible at every step, and designed so compliance evidence is generated by the infrastructure itself.",
    duration: "4–6 months (phased)",
    challenge:
      "The typical situation: a growing payment processor running on on-premise infrastructure. Peak transaction volumes cause slowdowns, compliance audits are increasingly complex, and the infrastructure team spends most of its time on maintenance rather than product work. The legacy setup can't scale for seasonal demand spikes, and provisioning new hardware is slow and expensive.",
    solution:
      "We'd design a phased migration to AWS, prioritizing the payment processing core and keeping a rollback path open at each phase. The target architecture: auto-scaling Kubernetes clusters (EKS), multi-region failover, and PCI-DSS-scoped infrastructure defined entirely as code so audit evidence is reproducible. Blue-green deployments allow shipping during business hours without risk, and an observability stack (Datadog or open-source equivalent) provides real-time monitoring and alerting from day one — not bolted on at the end.",
    results: [
      "Written migration strategy with phase gates and explicit rollback criteria",
      "Infrastructure-as-code repository (Terraform) covering the full PCI-DSS scope",
      "Auto-scaling EKS cluster design with multi-region failover runbook",
      "Blue-green deployment pipeline with automated smoke tests",
      "Observability stack with dashboards, SLO definitions, and alert routing",
      "Compliance evidence pack: architecture diagrams, data-flow maps, access-control matrix",
    ],
    technologies: [
      "AWS EKS",
      "Terraform",
      "ArgoCD",
      "PostgreSQL RDS",
      "Redis ElastiCache",
      "Datadog",
      "GitHub Actions",
    ],
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800",
    metrics: [
      { label: "Timeline", value: "4–6 months" },
      { label: "Budget Range", value: "€40–70K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
  {
    id: "2",
    slug: "analytics-platform-series-a",
    title: "How We'd Build a B2B Analytics MVP That Survives Due Diligence",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "Enterprise SaaS",
    description:
      "An engagement blueprint for taking a validated B2B analytics concept from Figma mockups to a production MVP that can pass investor technical due diligence — built to a funding deadline without cutting the corners investors check.",
    duration: "12–16 weeks",
    challenge:
      "The typical situation: a small founding team has validated a B2B analytics concept with pilot customers but lacks the engineering capacity to build the product. They need to go from mockups to a production MVP within months to hit a funding deadline, and interested investors will run technical due diligence on whatever gets built.",
    solution:
      "We'd embed as the interim engineering team, building the core platform with Next.js, Node.js, and PostgreSQL (TimescaleDB for the event pipeline) while establishing engineering practices from day one. The architecture is designed for projected 3-year growth without rewrites — but no earlier, because speculative infrastructure kills MVP timelines. Testing, CI/CD, and documentation are structured specifically to answer the questions VC technical reviewers actually ask: access controls, data model, key-person risk, and deployment story.",
    results: [
      "Production MVP: multi-tenant app, event ingestion pipeline, analytics dashboards",
      "CI/CD pipeline with automated tests and preview environments",
      "Architecture decision records and a due-diligence-ready documentation pack",
      "Stripe billing and Auth0 authentication wired for enterprise SSO later",
      "Handover plan: hiring guidance and onboarding docs for the first in-house engineer",
      "Post-launch support window with defined response times",
    ],
    technologies: [
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "TimescaleDB",
      "Redis",
      "AWS",
      "Stripe",
      "Auth0",
    ],
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800",
    metrics: [
      { label: "Timeline", value: "12–16 weeks" },
      { label: "Budget Range", value: "€35–60K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
  {
    id: "3",
    slug: "manufacturing-erp-modernization",
    title: "How We'd Modernize a 15-Year-Old ERP Without Stopping Production",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "Manufacturing / Industrial",
    description:
      "An engagement blueprint for incrementally modernizing a legacy custom ERP using the strangler fig pattern — because when downtime halts production lines, a big-bang rewrite is a bet-the-company move we'd refuse to make.",
    duration: "6–9 months (incremental)",
    challenge:
      "The typical situation: a manufacturing company runs critical operations on a 15-year-old custom ERP. The original developers are gone, documentation is sparse, and the codebase is nearly impossible to modify safely. Any downtime halts production, making a rewrite too risky — yet new customer EDI integration requirements are impossible to meet on the existing architecture.",
    solution:
      "We'd apply the strangler fig pattern: put a clean API layer in front of the legacy system, build new capabilities as small services behind it, and extract legacy modules one at a time — each extraction independently shippable and independently reversible. Message queues (RabbitMQ) decouple new services from legacy timing assumptions. Crucially, the internal team pairs with us throughout, so the engagement ends with them able to maintain and extend the system without us. We measure our success by our own obsolescence.",
    results: [
      "Legacy system audit: dependency map, risk register, and extraction sequence",
      "Anti-corruption API layer isolating legacy modules from new services",
      "First extracted modules shipped as documented, tested microservices",
      "EDI integration layer designed for onboarding additional customer systems",
      "Hands-on training plan and pairing sessions for the internal team",
      "Modernization playbook the team can continue executing independently",
    ],
    technologies: [
      "Node.js",
      "React",
      "PostgreSQL",
      "RabbitMQ",
      "Docker",
      "Azure",
      "Power BI",
    ],
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800",
    metrics: [
      { label: "Timeline", value: "6–9 months" },
      { label: "Budget Range", value: "€45–80K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
  {
    id: "4",
    slug: "healthcare-platform-scaleup",
    title: "How We'd Scale a Telehealth Platform and Reach Compliance",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "Healthcare / HealthTech",
    description:
      "An engagement blueprint for scaling a monolithic telehealth platform that's buckling under load, while building the compliance controls (GDPR, NEN 7510 / ISO 27001, HIPAA where relevant) that enterprise healthcare contracts require.",
    duration: "4–6 months",
    challenge:
      "The typical situation: a telehealth platform that grew fast is buckling under load. The monolith can't scale past a few hundred concurrent users, API responses stretch to multiple seconds, and the platform lacks the audit logging, encryption posture, and access controls that enterprise hospital contracts demand. Deals are being lost to competitors who can demonstrate compliance.",
    solution:
      "We'd start with a performance engineering sprint — query optimization, caching layers, connection pooling — because most 'we need microservices' problems are actually database problems. Then we'd decompose only the genuinely load-critical paths (appointments, records) into event-driven services with a CQRS read model, rather than rewriting everything. In parallel: end-to-end encryption, compliance-grade audit logging, and a controls mapping against the relevant framework (GDPR + NEN 7510 for Dutch healthcare; HIPAA for US contracts), producing the evidence pack enterprise procurement teams ask for.",
    results: [
      "Performance audit with prioritized bottleneck remediation plan",
      "Load-tested architecture with defined capacity targets and SLOs",
      "Event-driven decomposition of load-critical modules with CQRS read paths",
      "Encryption and audit-logging implementation mapped to compliance controls",
      "Compliance evidence pack for enterprise procurement and security reviews",
      "Load-testing harness (k6) the team can run before every release",
    ],
    technologies: [
      "Node.js",
      "React",
      "PostgreSQL",
      "Redis",
      "AWS ECS",
      "Terraform",
      "WebRTC",
      "Docker",
    ],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800",
    metrics: [
      { label: "Timeline", value: "4–6 months" },
      { label: "Budget Range", value: "€35–65K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
  {
    id: "5",
    slug: "ecommerce-performance-rescue",
    title: "How We'd Rescue an E-Commerce Platform Before Black Friday",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "E-Commerce / Retail",
    description:
      "An engagement blueprint for a performance rescue: a structured audit-first approach to an e-commerce platform that slows to a crawl under peak load — fixing root causes instead of adding servers.",
    duration: "2–3 months",
    challenge:
      "The typical situation: a mid-market retailer loses revenue every peak shopping period. Pages take many seconds to load under traffic, cart abandonment climbs, and the site has crashed during previous Black Friday events. A previous agency treated symptoms (bigger servers) without finding the architectural causes.",
    solution:
      "We'd run a one-week diagnostic first — real-user monitoring, load testing with k6, query analysis — and present findings before proposing fixes, so you can verify the diagnosis independently. Typical root causes in this scenario: unoptimized queries, missing caching, synchronous third-party API calls in the checkout path, and oversized frontend bundles. The remediation plan usually combines a multi-layer Redis caching strategy, server-side rendering with Next.js for critical pages, CDN edge caching, and moving inventory checks and payment validation to asynchronous processing. Then we'd load-test to an agreed traffic multiple before peak season — and publish the test results to you, whatever they show.",
    results: [
      "One-week performance diagnostic with evidence-backed root-cause report",
      "Prioritized remediation plan with effort estimates per fix",
      "Caching architecture (Redis + CDN edge) with cache-invalidation strategy",
      "Core Web Vitals optimization for critical purchase-path pages",
      "Load-test report at an agreed peak-traffic multiple, shared in full",
      "Peak-season runbook: monitoring dashboards, alert thresholds, rollback plan",
    ],
    technologies: [
      "Next.js",
      "Node.js",
      "Redis",
      "PostgreSQL",
      "Cloudflare CDN",
      "AWS",
      "Datadog",
      "Lighthouse",
    ],
    image: "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=800",
    metrics: [
      { label: "Timeline", value: "2–3 months" },
      { label: "Budget Range", value: "€15–35K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
  {
    id: "6",
    slug: "logistics-tech-due-diligence",
    title: "How We'd Run Technical Due Diligence for an Acquisition",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "Logistics / Private Equity",
    description:
      "An engagement blueprint for independent technical due diligence on a SaaS acquisition target: a fixed-scope, four-week deep dive that quantifies technical debt and security risk before money changes hands.",
    duration: "3–4 weeks (fixed scope)",
    challenge:
      "The typical situation: an investor is evaluating a SaaS company whose management claims a modern, scalable stack. The buyer needs independent verification before committing — because undisclosed technical debt discovered after closing routinely costs seven figures to remediate, and the seller's own materials are not a neutral source.",
    solution:
      "We'd run a fixed-scope, four-week assessment: architecture review, code quality analysis (SonarQube plus manual review of the riskiest modules), security posture review, load testing against claimed capacity, team and key-person-risk evaluation, and infrastructure cost analysis. The output is a report with per-system risk ratings, a quantified technical-debt estimate with the methodology shown (so you can challenge our numbers), and a prioritized post-acquisition remediation roadmap with cost estimates. We report what we find — including 'the stack is fine,' if it is.",
    results: [
      "Written due-diligence report with per-system risk ratings",
      "Technical-debt quantification with transparent estimation methodology",
      "Security findings with severity ratings and remediation costs",
      "Load-test results validating (or refuting) claimed scalability",
      "Team capability and key-person-risk assessment",
      "90-day post-acquisition remediation roadmap with cost estimates",
    ],
    technologies: [
      "Architecture Review",
      "Code Analysis",
      "Security Audit",
      "Load Testing",
      "k6",
      "SonarQube",
      "AWS Well-Architected",
    ],
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800",
    metrics: [
      { label: "Timeline", value: "3–4 weeks" },
      { label: "Budget Range", value: "€12–25K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
  {
    id: "7",
    slug: "insurance-ai-agent-deployment",
    title: "How We'd Deploy an EU AI Act-Compliant Customer Service Agent",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "Insurance / Financial Services",
    description:
      "An engagement blueprint for deploying a RAG-powered AI customer service agent in a regulated industry — with EU AI Act transparency controls, human escalation, and honest evaluation designed in from the start, not retrofitted.",
    duration: "3–4 months",
    challenge:
      "The typical situation: a customer service department is drowning in volume — tens of thousands of monthly inquiries across policy questions, claims status, and coverage changes. Wait times balloon, abandonment climbs, and experienced agents spend their days on routine queries while complex cases go understaffed. Leadership wants AI, but in insurance, a hallucinating chatbot is a regulatory and reputational liability.",
    solution:
      "We'd build a RAG-powered agent using Claude as the reasoning engine and Pinecone as the vector store, ingesting policy documentation and the knowledge base, integrated with the CRM via API orchestration. The non-negotiables in a regulated deployment: EU AI Act transparency controls (clear AI disclosure to customers), full audit logging of every interaction, and hard escalation triggers routing sensitive topics — claims disputes, cancellations, vulnerable customers — to humans. Before go-live, we'd run a shadow-mode evaluation against real historical inquiries and share the accuracy results with you, whatever they are. Automation rate targets get set from that evidence, not from a sales deck.",
    results: [
      "RAG agent with retrieval pipeline over policy docs and knowledge base",
      "CRM and core-system integration via API orchestration layer",
      "EU AI Act transparency package: AI disclosure, audit logging, human oversight",
      "Escalation framework with hard triggers for sensitive topics",
      "Shadow-mode evaluation report against historical inquiries, shared in full",
      "Monitoring dashboard: resolution rates, escalations, drift detection (LangFuse)",
    ],
    technologies: [
      "Claude API",
      "Pinecone",
      "LangChain",
      "Python/FastAPI",
      "AWS",
      "PostgreSQL",
      "n8n",
    ],
    image: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800",
    metrics: [
      { label: "Timeline", value: "3–4 months" },
      { label: "Budget Range", value: "€30–55K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
  {
    id: "8",
    slug: "fintech-eu-ai-act-compliance",
    title: "How We'd Run an EU AI Act Compliance Program for a FinTech",
    client: "Reference scenario — illustrative, not a client claim",
    industry: "FinTech / Regulatory",
    description:
      "An engagement blueprint for our flagship service: a four-phase EU AI Act compliance program for a FinTech running high-risk AI systems (fraud detection, credit scoring, onboarding) — engineering-led, ahead of the December 2027 high-risk deadline.",
    duration: "4–6 months (four phases)",
    challenge:
      "The typical situation: a FinTech has deployed AI across fraud detection, credit scoring, and customer onboarding — with no EU AI Act compliance framework. Several systems likely qualify as 'high-risk' under the Act, exposing the company to fines of up to 7% of global turnover. The high-risk compliance deadline (December 2, 2027, after the Digital Omnibus) is approaching, and enterprise partners are already asking AI Act questions in vendor reviews. The board wants a program, and lawyers alone can't build the technical controls the Act requires.",
    solution:
      "We'd execute a four-phase program. Phase 1: AI system inventory and risk classification against the Act's categories — this is where our €2,500 Quick Scan fits as a standalone starting point. Phase 2: Fundamental Rights Impact Assessments for high-risk systems. Phase 3: technical compliance controls — audit logging, bias monitoring, human override interfaces — built by engineers into the actual systems, which is the part legal consultancies can't deliver. Phase 4: governance framework, including an AI ethics board charter and staff training. Each phase ends with a documentation checkpoint structured for regulatory consultation and partner vendor reviews.",
    results: [
      "Complete AI system inventory mapped to EU AI Act risk categories",
      "Fundamental Rights Impact Assessments for each high-risk system",
      "Technical controls implemented: audit logging, bias monitoring, human override",
      "Article 11-aligned technical documentation per high-risk system",
      "Governance framework: AI ethics board charter, policies, staff training",
      "Vendor-review-ready compliance pack for enterprise partner questionnaires",
    ],
    technologies: [
      "Custom compliance tooling",
      "LangFuse",
      "Python",
      "Azure",
      "Power BI",
    ],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    metrics: [
      { label: "Quick Scan", value: "€2,500" },
      { label: "Full Program", value: "€25–60K" },
      { label: "Staffing", value: "Founder-led" },
    ],
  },
];
